//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoWeb {


    public partial class Registrar {

        protected global::System.Web.UI.WebControls.HiddenField hfCodigo;
        protected global::System.Web.UI.WebControls.HiddenField hfArticuloId;
        protected global::System.Web.UI.WebControls.TextBox txtDni;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtApellido;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.TextBox txtCiudad;
        protected global::System.Web.UI.WebControls.TextBox txtCP;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.Button btnParticipar;
    }
}