//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoWeb {


    public partial class SeleccionPremio {

        protected global::System.Web.UI.WebControls.HiddenField hfCodigo;
        protected global::System.Web.UI.WebControls.Repeater repPremios;
        protected global::System.Web.UI.WebControls.Label lblErr;
        protected global::System.Web.UI.WebControls.Button btnNext;
    }
}