//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoWeb {


    public partial class SiteMaster {

        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}